site_name: Task Badger Documentation
theme:
  name: material
  logo: assets/logo_white.png
  favicon: assets/favicon.ico
  palette:
    - scheme: indigo
  features:
    - navigation.tracking
    - content.code.annotate
    - content.tabs.link
markdown_extensions:
  - admonition
  - tables
  - def_list
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - assets/css/extra.css
