name: docs-deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: docs
      - uses: actions/checkout@v3
        with:
          repository: taskbadger/taskbadger-python
          path: taskbadger-python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: |
          cd docs
          mkdocs gh-deploy --force
